version: "1"
services:
  chat-bot:
    build: ChatBot
    ports:
      - "8086:8086"
    networks:
      - my-net

  postgres:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
        - "5432:5432"
    networks:
        - my-net
    volumes:
        - ./postgres-data:/var/lib/postgresql/data

  info-service:
    build:
      InfoService
    ports:
        - "8080:8080"
    networks:
      - my-net
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  statistics-service:
    build:
      StatisticService
    ports:
      - "8081:8081"
    networks:
      - my-net
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  load-generator:
    build:
      LoadGenerator
    ports:
      - "8082:8082"
    networks:
      - my-net

  recomendation-service:
    build:
      RecomendationService
    ports:
      - "8085:8085"
    networks:
      - my-net
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

networks:
  my-net: