version: '3.8'

services:
  neo4j:
    image: neo4j
    container_name: neo4j_container
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-data:/data


